apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  labels:
    app: backend
spec:
  replicas: 3   # 3 Pods should exist at all times.
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: mohamedahmedalakhdar/backend-image
        
        ports:
          - containerPort: 8080